import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "../../component/Context";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <div id="layout">{children}</div>
        </ContextProvider>
      </body>
    </html>
  );
}
