import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "../../component/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <div id="layout">{children}</div>
        </ContextProvider>
      </body>
    </html>
  );
}
